language: android
dist: trusty
andriod:
  components:
    - # Build tools
    - build-tools-29.0.2

    # Android SDK
    - android-29

      # Additional components
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository